"""Nuevo cambio

Revision ID: dba345a71836
Revises: 617fbcb3c9f5
Create Date: 2026-03-09 20:15:21.610378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dba345a71836'
down_revision = '617fbcb3c9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('users')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nombre'))

    op.drop_table('categorias')
    op.drop_table('ventas')
    op.drop_table('productos')
    op.drop_table('venta_detalles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venta_detalles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('venta_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('venta_detalles_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('venta_detalles_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('productos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('precio', mysql.FLOAT(), nullable=False),
    sa.Column('stock', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('imagen', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('productos_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ventas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('total', mysql.FLOAT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=50), server_default=sa.text("'completada'"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ventas_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categorias',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('activa', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nombre'), ['nombre'], unique=True)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'usuario'"), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
